import streamlit as st
from google import genai
from google.genai import types
import json
import tempfile
import os
import time

# ==========================================
# 1. PAGE SETUP & UI CONFIG
# ==========================================
st.set_page_config(page_title="Multi-Agent Researcher", page_icon="🎓", layout="wide")
st.title("🎓 Cater Family AI Researcher with Agenic Validation ")
# Create a text input for the password
password = st.sidebar.text_input("Enter Access Key", type="password")

# If the password doesn't match the one in your secrets, stop the app
if password != st.secrets["APP_PASSWORD"]:
    st.warning("Please enter the correct Access Key in the sidebar to use this research tool.")
    st.stop() # This prevents the rest of the code from running

# ==========================================
# 2. SESSION STATE (The "Memory")
# ==========================================
if "messages" not in st.session_state:
    st.session_state.messages = []

# ==========================================
# 3. SIDEBAR (Uploads & Clear Button)
# ==========================================
with st.sidebar:
    st.header("⚙️ Controls")
    st.markdown("Upload PDFs or text files. The AI will synthesize these alongside live Google Search results.")
    
    # Feature: Document Upload
    uploaded_files_ui = st.file_uploader("Upload Documents", accept_multiple_files=True)
    
    st.divider()
    
    # Feature: Clear All Option
    if st.button("🗑️ Clear Chat / Start Over", type="primary"):
        st.session_state.messages = []
        st.rerun()

# ==========================================
# 4. AUTHENTICATION & API SETUP
# ==========================================
# IMPORTANT: Replace with your actual API key
API_KEY = st.secrets["GEMINI_API_KEY"]
client = genai.Client(api_key=API_KEY)

# ==========================================
# 5. THE SYSTEM PROMPTS
# ==========================================
agent_a_prompt = """
Role: You are a highly rigorous, technical research assistant. Your primary directive is absolute factual accuracy. All research, analysis, and explanations must be delivered at the academic and technical depth of a Master's degree graduate.

Core Directives:
1. Handling Uncertainty: If you lack high confidence, state ONLY: "I cannot provide a reliable answer." Silence is strictly preferred over a confident error.
2. Academic Consensus: If a topic lacks consensus, map out the leading competing theories citing foundational sources.
3. Estimations: Never guess. Preface estimations with: "Warning: The following is an estimation/theoretical model and may not be definitive."
4. Blended Sourcing: You have access to Google Search and User Documents. Give equal weight to both. Synthesize facts into a single cohesive response.

Mandatory Verification Protocol:
Generate a [VERIFICATION LOG] block at the top containing:
* Source Check (State if you used web search, documents, or both)
* Quote/Canonical Source Extraction
* Consensus Check
* Confidence Check

Output a horizontal line (---), then the final response.
"""

agent_b_prompt = """
You are a ruthless, highly critical peer reviewer.
Review the draft response generated by Agent A based on the user's latest query.
1. Check for hallucinated sources. 
2. Ensure no guessing or unsupported claims. 
Output ONLY strict JSON in this exact format:
{"status": "PASS", "feedback": ""} OR {"status": "FAIL", "feedback": "Explanation of what is wrong."}
"""

# ==========================================
# 6. THE MULTI-AGENT PIPELINE
# ==========================================

def process_files(files):
    """Saves files to temp and uploads with retry logic for Windows stability."""
    gemini_files = []
    for f in files:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            tmp.write(f.getbuffer())
            tmp_path = tmp.name
        
        # Retry Mechanism to handle WinError 10054
        success = False
        for attempt in range(3):
            try:
                g_file = client.files.upload(
                    file=tmp_path, 
                    config={'display_name': f.name}
                )
                gemini_files.append(g_file)
                success = True
                break 
            except Exception as e:
                if attempt < 2:
                    time.sleep(2) # Wait and retry
                    continue
                else:
                    st.error(f"Error uploading {f.name}: Connection dropped by server.")
            finally:
                if success and os.path.exists(tmp_path):
                    os.remove(tmp_path)
    return gemini_files

def run_research_pipeline(user_input, chat_history, files):
    status_box = st.empty()
    status_box.info("Initializing multi-agent analysis...")

    # Configs
    config_a = types.GenerateContentConfig(
        system_instruction=agent_a_prompt, 
        temperature=0.0,
        tools=[types.Tool(google_search=types.GoogleSearch())]
    )
    
    config_b = types.GenerateContentConfig(
        system_instruction=agent_b_prompt, 
        temperature=0.0, 
        response_mime_type="application/json"
    )
    
    # Build Conversation History
    contents_a = []
    for msg in chat_history:
        role = "user" if msg["role"] == "user" else "model"
        contents_a.append({"role": role, "parts": [{"text": msg["content"]}]})
    
    # Upload and append files/current prompt
    gemini_files = process_files(files) if files else []
    current_parts = gemini_files + [{"text": user_input}]
    contents_a.append({"role": "user", "parts": current_parts})

    # Agent A Phase
    status_box.info("Agent A is synthesizing web search and document data...")
    response_a = client.models.generate_content(model='gemini-2.5-flash', contents=contents_a, config=config_a)
    draft_response = response_a.text
    
    # Agent B Phase (Review Loop)
    attempt = 0
    max_retries = 2
    while attempt < max_retries:
        status_box.warning(f"Agent B is conducting Peer Review (Attempt {attempt + 1})...")
        
        review_prompt = f"User Query: {user_input}\n\nDraft:\n{draft_response}"
        response_b = client.models.generate_content(model='gemini-2.5-flash', contents=review_prompt, config=config_b)
        
        try:
            critique_data = json.loads(response_b.text)
            status = critique_data.get("status")
            feedback = critique_data.get("feedback")
        except:
            status = "FAIL"
            feedback = "Critical logic error in peer review formatting."
            
        if status == "PASS":
            status_box.success("Final Response Approved by Critic.")
            return draft_response
        else:
            status_box.error(f"Review Failed: {feedback}")
            st.toast("Agent A is revising...")
            
            revision_prompt = f"Your draft failed review. Fix these issues: {feedback}"
            revision_contents = contents_a + [
                {"role": "model", "parts": [{"text": draft_response}]}, 
                {"role": "user", "parts": [{"text": revision_prompt}]}
            ]
            
            response_a_revised = client.models.generate_content(model='gemini-2.5-flash', contents=revision_contents, config=config_a)
            draft_response = response_a_revised.text
            
        attempt += 1
        
    status_box.info("Research complete (reached max validation loops).")
    return draft_response

# ==========================================
# 7. THE CHAT INTERFACE
# ==========================================
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask a follow-up or a new research query..."):
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        final_output = run_research_pipeline(prompt, st.session_state.messages, uploaded_files_ui)
        st.markdown(final_output)

    # Save to Session State
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.session_state.messages.append({"role": "assistant", "content": final_output})
